### ISSUE TITLE
Test upload

### ISSUE THREAD

**Issue by rguillens** [adfemg/task-flow-tester#4]
The tester page needs to declare it uses upload to allow uploading files.

**Comment by acelopezco** [comment]
Hi @rguillens 
I think this was made by design. I remember there were some documentation about how to extend the  taskflow tester to include more features without affecting the base code. Unfortunately I cannot find it now that java.net is gone. Perhaps @wvanderdeijl or @RichardOlrichs remember this. Anyway, adding usesUpload to the main form is a simple task, I'm just not sure if it's a good idea.

Found this question in oracle forums from when, I suppose, the task flow tester was being designed:
https://community.oracle.com/thread/1005064

**Comment by rguillens** [comment]
Hi @aalopez
I think it's a good idea, at least is better than the solution we have now: creating new test pages for testing uploading files.
I think a solution to test taskflows that upload files is a missing feature and should be provided by taskflow tester.
I looked about ```usesUpload``` and it's impact on performance and it's no so bad, however, there may be other solutions. Maybe setting ```usesUpload``` property on the main form; maybe in a new special page and taskflow just for this use case.

**Comment by acelopezco** [comment]
mhmh... still not sure why it is not implemented that way. If you look at the project's wiki, you'll find a page that tells you how to extend the taskflow tester and gives you an example. It also mentions the usesUpload case:
https://github.com/adfemg/task-flow-tester/wiki/Creating-Custom-Tester-Launch-Page

Problem is, I'm not sure if that's reusable among projects.

Hey @RichardOlrichs can you give us a hand here, please?

**Comment by rguillens** [comment]
My bad, I didn't knew about Custom Tester Launch Pages. And yes, this can be distributed and reused in many ways, in my case using Maven.

Thanks a lot.
